'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Item={id:string;title:string;description:string|null;status:string;created_at:string}
export default function Dashboard({email,initialItems}:{email:string;initialItems:Item[]}){const [items,setItems]=useState(initialItems);const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [prompt,setPrompt]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false)
async function addItem(e:React.FormEvent){e.preventDefault();if(!title.trim())return;const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data}=await s.from('dashboard_items').insert({title,description,user_id:user.id}).select('id,title,description,status,created_at').single();if(data)setItems([data,...items]);setTitle('');setDescription('')}
async function removeItem(id:string){const s=createClient();await s.from('dashboard_items').delete().eq('id',id);setItems(items.filter(x=>x.id!==id))}
async function ask(e:React.FormEvent){e.preventDefault();if(!prompt.trim())return;setBusy(true);setAnswer('');const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt})});const d=await r.json();setAnswer(d.text??d.error);setBusy(false)}
async function logout(){await createClient().auth.signOut();window.location.href='/auth/login'}
return <main className="app-shell"><header className="topbar"><div className="brand-mark"><span>✳</span> signal</div><div className="top-actions"><span className="user-email">{email}</span><button className="text-button" onClick={logout}>Log out</button></div></header><section className="hero"><div><div className="eyebrow">MONDAY, SEPTEMBER 30</div><h1>Make room for<br/><em>clear thinking.</em></h1><p className="hero-copy">Your focused space for capturing what matters,<br/>then moving it forward.</p></div><div className="hero-orb"><span>✦</span></div></section><div className="dashboard-grid"><section className="panel items-panel"><div className="eyebrow">YOUR BOARD</div><h2>Active signals <span>{items.length}</span></h2><form className="add-form" onSubmit={addItem}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs your attention?"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add a little context (optional)"/><button className="primary-button">Add signal <span>↗</span></button></form><div className="item-list">{items.length===0?<div className="empty-state">Your board is clear.<br/>Add the first signal to begin.</div>:items.map(item=><article className="signal-item" key={item.id}><div className="signal-dot"/><div className="signal-content"><h3>{item.title}</h3>{item.description&&<p>{item.description}</p>}</div><button className="delete-button" aria-label={`Delete ${item.title}`} onClick={()=>removeItem(item.id)}>×</button></article>)}</div></section><section className="panel ai-panel"><div className="eyebrow">SIGNAL AI</div><h2>A second<br/><em>perspective.</em></h2><p className="muted">Bring a question, decision, or rough idea. Get a sharper way forward.</p><form onSubmit={ask} className="ai-form"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="What are you thinking about?" rows={4}/><button className="dark-button" disabled={busy}>{busy?'Thinking…':'Ask Signal'} <span>↗</span></button></form>{answer&&<div className="ai-answer"><div className="eyebrow">RESPONSE</div><p>{answer}</p></div>}</section></div></main>}
